### ISSUE TITLE
말하기 연습 GPT가 똑같은 질문만 반복하는 현상

### ISSUE THREAD

**Issue by gyuray-dev** [Sonjoonyong/gpteacherproject#121]
- 토익, 토플, 오픽 등 어떤 시험을 선택해도 취미가 뭐냐고 물어봅니다
- 인터넷 또는 GPT를 통해 기출 문제 100개 정도 뽑아서 랜덤 질문 유도할 때 한 개씩 랜덤으로 섞어주는 방식이 괜찮아 보입니다

**Comment by Sonjoonyong** [comment]
요거는 Write도 주제 만들어줄 때 다양성이 부족하긴해서 확인해보아야 할 듯 하네요

**Comment by gyuray-dev** [comment]
질문 요청 시 temperature 향상으로 해결했습니다.
