### ISSUE TITLE
말하기 연습 아무 말도 안 하고 제출할 때 비속어 필터링 에러 터짐

### ISSUE THREAD

**Issue by gyuray-dev** [Sonjoonyong/gpteacherproject#122]
- Whisper API로 빈 문자열까지는 출력되는데, 이 빈 문자열이 비속어 필터링 API로 들어가면서 에러가 터집니다.
- speakingPractice.jsp 270라인 코드 오류로 추정되네요.

**Comment by KangSuA** [comment]
네 오늘 안으로 수정해보겠습니다.
