### ISSUE TITLE
회화

### ISSUE THREAD

**Issue by Sonjoonyong** [Sonjoonyong/gpteacherproject#151]
녹음 최대 시간 1500초?

**Comment by Sonjoonyong** [comment]
<img width="492" alt="스크린샷 2023-05-04 오전 9 33 59" src="https://user-images.githubusercontent.com/124243338/236079601-49255d3c-d323-46ab-96a2-c05f3ebbb37d.png">

**Comment by gyuray-dev** [comment]
수정했습니다!
