### ISSUE TITLE
로그인시 가끔 새창

### ISSUE THREAD

**Issue by Sonjoonyong** [Sonjoonyong/gpteacherproject#153]
로그인 아이디 비밀번호 입력하고 로그인 버튼을 누르는게 아니라 엔터로 누르면 가끔 새창에서 다음 페이지가 열릴 때가 있음

**Comment by gyuray-dev** [comment]
shift를 누른채로 엔터를 누르면 그렇게 되는 것 같습니다. 너무 급하게 로그인 하셔서?! ㅋㅋ

**Comment by Sonjoonyong** [comment]
확인했습니다 ~
