### ISSUE TITLE
커뮤니티 게시글 '불법'으로 신고해도 사유가 '욕설'로 등록됨

### ISSUE THREAD

**Issue by gyuray-dev** [Sonjoonyong/gpteacherproject#154]
재현 과정
- 게시글 아무거나 '불법' 사유로 신고
- 신고 글 목록에서 조회하면 사유에 '욕설'로 조회됨

**Comment by gitman82** [comment]
불법사유로 신고시 관리자 페이지에서 불법으로 조회되게끔 수정했습니다
