### ISSUE TITLE
회화 처음 입력란에 a, b, c, d, e 입력하고 시작하면

### ISSUE THREAD

**Issue by Sonjoonyong** [Sonjoonyong/gpteacherproject#159]
<img width="1076" alt="스크린샷 2023-05-04 오전 9 52 13" src="https://user-images.githubusercontent.com/124243338/236082825-ddec9689-6e4b-4dd2-ba16-72868f6ed1b2.png">

**Comment by gyuray-dev** [comment]
진행중입니다.

**Comment by gyuray-dev** [comment]
검증이 쉽지 않네요 :(
