### ISSUE TITLE
회화 처음 입력란에 스페이스바만 입력하고 시작하면

### ISSUE THREAD

**Issue by Sonjoonyong** [Sonjoonyong/gpteacherproject#160]
<img width="1162" alt="스크린샷 2023-05-04 오전 9 54 48" src="https://user-images.githubusercontent.com/124243338/236083002-a420851f-f065-46b0-bc27-1566eb57edf1.png">

고장나버림

**Comment by gyuray-dev** [comment]
진행중입니다

**Comment by gyuray-dev** [comment]
프론트 사이드 유효성 검증 추가했습니다.
비정상 경로로 공백 input을 시도하는 유저까지는 굳이 차단할 필요는 없을 것 같아서 서버단 검증은 생략했습니다.
