### ISSUE TITLE
문의사항

### ISSUE THREAD

**Issue by KangSuA** [Sonjoonyong/gpteacherproject#163]
- 관리자 로그인 시 회원의 글 / 댓글 수정 가능
- 관리자가 댓글 하나도 안 달아도 답변 상태 변경 가능

**Comment by gitman82** [comment]
일단 여러가지 시도하면서 진행중

**Comment by gitman82** [comment]
여러가지 시도하면서 일단 진행중입니다.

**Comment by YunDDDDD** [comment]
수정중입니다.

**Comment by Sonjoonyong** [comment]
대현님이 회원의 문의게시글 관리자가 수정 못하게끔 프론트단에서 막아주셨고,
댓글 안달아도 답변 상태 변경 가능한 것은 제가 수정해보겠습니다.

**Comment by Sonjoonyong** [comment]
댓글 없을 시 버튼 비활성화 처리
