### ISSUE TITLE
글쓰기 연습 글자 제한이 필요합니다

### ISSUE THREAD

**Issue by gyuray-dev** [Sonjoonyong/gpteacherproject#164]
GPT API 1회 통신량이 4096 토큰인데, 답변까지 생각하면 절반인 2000토큰, 지시문까지 생각하면 약 1500토큰 이내로 사용자 인풋이 들어와야 합니다. 1500토큰이면 약 1125단어인데, 마진까지 생각해서 1000 ~ 1500글자정도로 제한하면 괜찮을 것 같네요.

**Comment by Sonjoonyong** [comment]
우선 프론트단에서 영어기준 1500자 제한 걸어두었습니다
