### ISSUE TITLE
회원가입 / 회원수정 유효성검사

### ISSUE THREAD

**Issue by KangSuA** [Sonjoonyong/gpteacherproject#165]
**버그는 아닙니다!**
- 비밀번호와 닉네임도 아이디와 같이 유효성 검사에 대한 설명이 추가되면 좋을 것 같습니다.

**Comment by Sonjoonyong** [comment]
개인적으로 인증 후 정보 수정 말고 해당 부분은 '인증' 으로 두고 인증 완료되면 인증완료로 되고
아래에 최종적인 submit버튼 또한 있는것이 더 좋아보입니다

**Comment by gyuray-dev** [comment]
넵 두 가지 부분 수정 진행하겠습니다.

**Comment by gyuray-dev** [comment]
수정 완료했습니다.
