### ISSUE TITLE
회원조회, 신고관리 sweetalert 적용불가한지?

### ISSUE THREAD

**Issue by Sonjoonyong** [Sonjoonyong/gpteacherproject#173]
차단하시겠습니까, 차단사유입력, 차단해제하시겠습니까 <--

**Comment by KangSuA** [comment]
관리자 페이지라 따로 안 넣었습니다. 변경할까요?

**Comment by Sonjoonyong** [comment]
시간이 좀 걸릴 것 같으면 그대로 둬도 될 것 같은데 시간이 남으면 처리해둬도 나쁘지 않을 것 같습니다!

**Comment by gyuray-dev** [comment]
대현님이 수정해주셨습니다~
