### ISSUE TITLE
커뮤니티 글작성

### ISSUE THREAD

**Issue by Sonjoonyong** [Sonjoonyong/gpteacherproject#176]
<img width="1479" alt="스크린샷 2023-05-04 오후 1 45 36" src="https://user-images.githubusercontent.com/124243338/236114474-9c3fc33f-c9e0-4c57-bad3-4b307bd1e983.png">

+ 화면 이상함
+ 나의 문장 첨부 응답없음
+ 마크다운 <-> 워지윅 아직 수정 안됨

**Comment by gitman82** [comment]
<img width="1037" alt="스크린샷 2023-05-04 오후 1 48 10" src="https://user-images.githubusercontent.com/104996232/236114805-085443b1-bc24-4c4e-a057-b05f783f3f8e.png">
<img width="1039" alt="스크린샷 2023-05-04 오후 1 48 20" src="https://user-images.githubusercontent.com/104996232/236114823-3bc31795-328a-4ab3-a267-694a91a8a77e.png">




곧 다시 pull requests 하겠습니다

**Comment by Sonjoonyong** [comment]
여전히 처음에 유저가 글 작성할 때 위지윅 누르면 글 내용 사라짐 default값을 주거나 해야할 듯 함

**Comment by gitman82** [comment]
js부분 오류였는데 은규님이 수정하셨다고 했으니 곧 은규님이 올리실때 pull 하심 될 거 같습니다.

**Comment by gyuray-dev** [comment]
CSS 누락 및 브라우저 캐시 문제였습니다 - 해결 완료
