### ISSUE TITLE
회화 랜덤 추천으로 대화시작시 비정상적인 대화 출력(몇몇 프롬프트)

### ISSUE THREAD

**Issue by Sonjoonyong** [Sonjoonyong/gpteacherproject#180]
<img width="997" alt="스크린샷 2023-05-04 오후 2 37 10" src="https://user-images.githubusercontent.com/124243338/236120562-083f3b40-57a9-43ac-b24e-d531a63fa5ee.png">
<img width="1064" alt="스크린샷 2023-05-04 오후 2 37 01" src="https://user-images.githubusercontent.com/124243338/236120578-8e96e1b2-90bf-46f0-9bb6-56d7cf4384a7.png">
<img width="1114" alt="스크린샷 2023-05-04 오후 2 38 34" src="https://user-images.githubusercontent.com/124243338/236120598-d7abd15b-8c35-4d6f-8fc3-3942398fe86b.png">
<img width="1140" alt="스크린샷 2023-05-04 오후 2 38 42" src="https://user-images.githubusercontent.com/124243338/236120610-07b5d5f1-0534-4bb6-84d8-775e5027f8fd.png">

**Comment by gyuray-dev** [comment]
해결완료했습니다.
#192
