### ISSUE TITLE
글쓰기 문장 분석 중에도 수정 가능

### ISSUE THREAD

**Issue by KangSuA** [Sonjoonyong/gpteacherproject#190]
글쓰기 분석 버튼 클릭 후 로딩 아이콘 진행 중에도 글 내용 수정이 가능합니다. 
버튼을 누른 후에는 수정이 불가능하도록 해두어야 할 것 같습니다.

**Comment by Sonjoonyong** [comment]
ing

**Comment by YunDDDDD** [comment]
풀 받아서 확인해봤는데 잘 고쳐졌습니다.
