### ISSUE TITLE
커뮤니티 좋아요

### ISSUE THREAD

**Issue by KangSuA** [Sonjoonyong/gpteacherproject#191]
- 커뮤니티 리스트 페이지에 좋아요 하지 않은 게시글 하트가 꽉찬 하트로 보입니다.
- 좋아요가 0개인 게시물만 빈하트로 보입니다.
- 내가 좋아요한 글만 꽉찬 하트로 보이는게 더 좋은 것 같아 의견 남겨봅니다.....

**Comment by gitman82** [comment]
고쳐보고 올게요

**Comment by gyuray-dev** [comment]
일부러 그렇게 했는데 혹시 시간이 남으면 바꿔보겠습니다!
