### ISSUE TITLE
게시판 글 제목 정렬

### ISSUE THREAD

**Issue by gyuray-dev** [Sonjoonyong/gpteacherproject#195]
지금 왼쪽 정렬, 가운데 정렬이 혼재 돼있는데 왼쪽 정렬로 통일하면 좋을 것 같습니다.
현재 가운데 정렬인 게시판
- 공지사항
- 문의사항
- 회원 조회 -> 작성 글 목록
- 신고 글 목록
- 신고 댓글 목록

**Comment by KangSuA** [comment]
제가 코드 수정 하겠습니다.
