### ISSUE TITLE
문의사항 답변 상태

### ISSUE THREAD

**Issue by gyuray-dev** [Sonjoonyong/gpteacherproject#197]
문의사항 작성일 오른쪽에 답변 상태 간단하게 표시하면 좋을 것 같습니다.
또 답변 완료에서 답변중으로는 변경하지 못하니 상태 변경 후에는 버튼도 숨기면 괜찮을 것 같아요.

**Comment by YunDDDDD** [comment]
해결중!

**Comment by YunDDDDD** [comment]
풀받고 이상 없으면 닫겠습니다.

**Comment by Sonjoonyong** [comment]
닫아드리겠습니다
