### ISSUE TITLE
신고 글/댓글 목록 링크 하이라이팅

### ISSUE THREAD

**Issue by gyuray-dev** [Sonjoonyong/gpteacherproject#198]
![image](https://user-images.githubusercontent.com/121680816/236507999-955fcc7c-6bb5-410f-a417-e583578f3f44.png)

방문한 링크랑 안 한 링크랑 색깔 차이가 있습니다. 신고 데이터를 SQL로 넣다보니 이런 현상이 있는데, 실제 운영 시 어드민은 이렇게 보이게 될 것 같습니다.

**Comment by KangSuA** [comment]
제가 코드 수정 하겠습니다.
